server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

plugins:
  youtube:
    enabled: true
    oauth:
      enabled: false
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
      - MWEB
      - WEB
      - MUSIC
      - WEBEMBEDDED
      - TV
    clientOptions:
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: false
      WEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      MWEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true

  lavasrc:
    providers:
      - "dzisrc:%ISRC%"
      - "dzsearch:%QUERY%"
      - "jssearch:%QUERY%"
      - "gaanasearch:%QUERY%"
      - "amkearch:%QUERY%"
      - "ytmsearch:%QUERY%"
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: false
      flowerytts: false
      youtube: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: true
      gaana: true
      audiomack: true
    lyrics-sources:
      spotify: false
      deezer: false
      youtube: false
      yandexmusic: false
      vkmusic: false
      lrcLib: false
    spotify:
      countryCode: "US"
      playlistLoadLimit: 3
      albumLoadLimit: 2
      resolveArtistsInSearch: true
      localFiles: true
      preferAnonymousToken: true
      preferPartnerApi: true
      preferV1SearchApi: false
      customTokenEndpoint: "http://localhost:8080/api/token"
    applemusic:
      countryCode: "US"
      mediaAPIToken: "your apple music api token"
      playlistLoadLimit: 3
      albumLoadLimit: 3
    deezer:
      masterDecryptionKey: "your master decryption key"
      arl: "your deezer arl"
      formats: ["MP3_256", "MP3_128", "MP3_64", "AAC_64" ]
    youtube:
      countryCode: "US"
      language: "en"
    jiosaavn:
      decryption:
        secretKey: "??"
        algorithm: "DES"
        transformation: "DES/ECB/PKCS5Padding"
    gaana:
      searchLimit: 20
    audiomack:
      accessToken: "your access token"
      accessSecret: "your access secret"
      searchLimit: 20



lavalink:
  pluginsDir: './plugins'
  server:
    password: "boombj"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    nonAllocatingFrameBuffer: false
    bufferDurationMs: 225
    frameBufferDurationMs: 5000
    opusEncodingQuality: 5
    resamplingQuality: LOW
    trackStuckThresholdMs: 5000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 3
    playerUpdateInterval: 3
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    youtubeConfig:
      email: "your account mail"
      password: "your account password"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 5
    max-size: 10MB
    path: ./logs/
  level:
    root: DEBUG
    lavalink: DEBUG
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: true
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
